'use client'

import { useMemo, useState } from 'react'
import { useLocale } from 'next-intl'
import InstrumentShell, { InstrumentButton, InstrumentResult } from './InstrumentShell'
import { useInstrumentProgress } from './useInstrumentProgress'
import { GRAVITY_FIXED_LEVELS, applyGravityRule, generateGravityLevel, getGravityHint, isGravitySolved, parseGravityRule, type GravityObject, type GravityWord } from '@/lib/impossible-instruments/gravity-grammar'
import { dailySeed } from '@/lib/impossible-instruments/core'

const COLOR: Record<string, string> = { RED: '#e86a5a', BLUE: '#5aa9e6', GOLD: '#e9c46a' }
export default function GravityGrammarGame() {
  const zh = useLocale() === 'zh'; const [levelIndex, setLevelIndex] = useState(0); const [infiniteRound, setInfiniteRound] = useState(0)
  const level = useMemo(() => levelIndex < 6 ? GRAVITY_FIXED_LEVELS[levelIndex] : generateGravityLevel(`${dailySeed('gravity-grammar')}:${infiniteRound}`, infiniteRound > 2 ? 'hard' : 'standard'), [levelIndex, infiniteRound])
  const [object, setObject] = useState<GravityObject>(level.object); const [sentence, setSentence] = useState<GravityWord[]>([level.object.color, 'PULLS', 'UP']); const [runs, setRuns] = useState(0); const [hints, setHints] = useState(0); const [score, setScore] = useState(0); const [solved, setSolved] = useState(false); const [message, setMessage] = useState(''); const { best, record } = useInstrumentProgress('gravity-grammar')
  const selectWord = (word: GravityWord) => { if (solved) return; if (['RED', 'BLUE', 'GOLD'].includes(word)) setSentence([word, sentence[1], sentence[2]]); else if (word === 'PULLS') setSentence([sentence[0], word, sentence[2]]); else setSentence([sentence[0], sentence[1], word]); setMessage('') }
  const run = () => { if (!parseGravityRule(sentence)) { setMessage(zh ? '句法无效。' : 'Invalid grammar.'); return } const nextObject = applyGravityRule(level, object, sentence); const nextRuns = runs + 1; setObject(nextObject); setRuns(nextRuns); if (nextObject.row === object.row && nextObject.col === object.col) setMessage(zh ? '规则主语与物体不匹配。' : 'The rule does not name this object.'); else setMessage(''); if (isGravitySolved(level, nextObject)) { const earned = Math.max(150, 700 - nextRuns * 35 - hints * 80); setScore((v) => v + earned); setSolved(true); record(Math.min(levelIndex + 1, 6), score + earned) } }
  const hint = () => { const direction = getGravityHint(level, object); setSentence([object.color, 'PULLS', direction]); setHints((v) => v + 1); setMessage(zh ? '仪器已排出下一步有效句。' : 'The instrument composed one useful sentence.') }
  const next = () => { const ni = levelIndex < 5 ? levelIndex + 1 : 6; const nr = levelIndex < 5 ? infiniteRound : infiniteRound + 1; const nl = ni < 6 ? GRAVITY_FIXED_LEVELS[ni] : generateGravityLevel(`${dailySeed('gravity-grammar')}:${nr}`, nr > 2 ? 'hard' : 'standard'); setLevelIndex(ni); setInfiniteRound(nr); setObject(nl.object); setSentence([nl.object.color, 'PULLS', 'UP']); setRuns(0); setHints(0); setSolved(false); setMessage('') }
  const aside = <><div className="border border-white/15 bg-black/20 p-4"><p className="font-mono text-[9px] tracking-widest text-[var(--instrument-accent)]">{zh ? '当前物理句' : 'ACTIVE PHYSICS SENTENCE'}</p><p className="mt-3 font-serif text-xl font-black">{sentence.join(' ')}</p><p className="mt-2 text-xs text-white/40">{zh ? '句子每运行一次，匹配的物体移动一格。' : 'Each run moves the named object by one cell.'}</p></div><InstrumentButton onClick={run} primary disabled={solved}>{zh ? '执行句子' : 'Execute sentence'}</InstrumentButton><InstrumentButton onClick={hint} disabled={solved}>{zh ? '自动排出一步' : 'Compose one step'}</InstrumentButton>{message && <p className="border border-[var(--instrument-accent)]/40 p-3 text-xs text-[var(--instrument-accent)]">{message}</p>}<div className="border border-white/10 p-3 font-mono text-xs text-white/45">RUNS {runs}/{level.maxRuns} · BEST {best}</div>{solved && <InstrumentResult title={zh ? '物理语法稳定' : 'Physical grammar stabilized'} detail={`${runs} executions`} onNext={next} nextLabel={levelIndex < 5 ? (zh ? '下一记录' : 'Next record') : (zh ? '持续观测' : 'Infinite observation')} />}</>
  return <InstrumentShell id="gravity-grammar" level={Math.min(levelIndex + 1, 6)} levelCount={6} score={score} hints={hints} aside={aside}><div><div className="mx-auto grid aspect-square max-w-[560px] border border-white/15 bg-[#e9dfca] p-2" style={{ gridTemplateColumns: `repeat(${level.size},1fr)` }}>{Array.from({ length: level.size * level.size }, (_, index) => { const row = Math.floor(index / level.size); const col = index % level.size; const occupied = object.row === row && object.col === col; const exit = level.exit.row === row && level.exit.col === col; return <div key={index} className="relative flex items-center justify-center border border-[#544b3d]/20">{exit && <span className="absolute inset-2 border-2 border-dashed border-[#3b7d5c] text-center text-[#3b7d5c]">EXIT</span>}{occupied && <span className="z-10 flex h-1/2 w-1/2 items-center justify-center rounded-full font-mono text-[10px] font-black text-white shadow-lg" style={{ backgroundColor: COLOR[object.color] }}>{object.color[0]}</span>}</div> })}</div><div className="mt-7 border-t border-white/10 pt-5"><p className="mb-3 font-mono text-[10px] tracking-wider text-white/40">{zh ? '点击铅字改写物理定律' : 'CLICK TYPE BLOCKS TO REWRITE PHYSICS'}</p><div className="flex flex-wrap gap-2">{level.words.map((word, index) => <button key={`${word}-${index}`} type="button" onClick={() => selectWord(word)} className={`min-h-11 border px-4 font-serif font-black transition ${sentence.includes(word) ? 'border-[var(--instrument-accent)] bg-[var(--instrument-accent)] text-[#17120d]' : 'border-white/20 hover:border-white'}`}>{word}</button>)}</div></div></div></InstrumentShell>
}
