'use client'

import { useEffect, useState } from 'react'
import { useLocale } from 'next-intl'
import { Link } from '@/i18n/routing'
import { INSTRUMENTS, INSTRUMENT_IDS, INSTRUMENT_PROGRESS_KEY, parseInstrumentProgress, type InstrumentProgress } from '@/lib/impossible-instruments/core'

export default function InstrumentCabinet() {
  const zh = useLocale() === 'zh'
  const [progress, setProgress] = useState<InstrumentProgress>(() => parseInstrumentProgress(null))
  useEffect(() => { try { setProgress(parseInstrumentProgress(localStorage.getItem(INSTRUMENT_PROGRESS_KEY))) } catch {} }, [])
  const stabilized = INSTRUMENT_IDS.filter((id) => (progress.completed[id] ?? 0) >= 6).length
  return <main className="relative min-h-screen overflow-hidden bg-[#17130e] text-[#efe5d2]"><div className="pointer-events-none absolute inset-0 opacity-30" style={{ backgroundImage: 'radial-gradient(#d0b78b 0.7px, transparent 0.7px), linear-gradient(115deg, transparent 49%, rgba(204,173,121,.08) 50%, transparent 51%)', backgroundSize: '17px 17px, 240px 240px' }} /><div className="relative mx-auto max-w-7xl px-4 py-12 sm:px-7 lg:py-20"><header className="grid gap-7 border-b border-[#d0b78b]/25 pb-10 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="font-mono text-[10px] font-black tracking-[.35em] text-[#d4a85f]">RESTRICTED COLLECTION / CABINET 13</p><h1 className="mt-5 font-serif text-[clamp(3.5rem,9vw,8rem)] font-black leading-[.78] tracking-[-.07em]">{zh ? '不可能' : 'IMPOSSIBLE'}<span className="block italic text-[#d4a85f]">{zh ? '仪器馆' : 'INSTRUMENTS'}</span></h1></div><div className="border-l border-[#d4a85f] pl-5"><p className="text-sm leading-7 text-white/55">{zh ? '六台拒绝遵守普通规则的仪器。观察、实验，并让它们重新稳定。' : 'Six instruments that refuse ordinary rules. Observe, experiment, and return each one to stability.'}</p><p className="mt-4 font-mono text-xs text-[#d4a85f]">{stabilized}/6 STABILIZED</p></div></header><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{INSTRUMENT_IDS.map((id) => { const item = INSTRUMENTS[id]; const completed = progress.completed[id] ?? 0; const stable = completed >= 6; return <article key={id} className="group relative flex min-h-[330px] flex-col overflow-hidden border border-white/15 bg-black/20 p-5 transition hover:-translate-y-1 hover:border-[var(--card-accent)]" style={{ '--card-accent': item.accent } as React.CSSProperties}><div className="absolute -right-8 -top-10 font-serif text-[10rem] text-white/[.035]">{item.glyph}</div><div className="relative flex items-start justify-between"><span className="font-mono text-xs font-black tracking-[.2em] text-[var(--card-accent)]">{item.file}</span><span className={`border px-2 py-1 font-mono text-[8px] ${stable ? 'border-[#74ca9c] text-[#74ca9c]' : 'border-white/15 text-white/35'}`}>{stable ? 'STABLE' : `${completed}/6`}</span></div><div className="relative mt-8 text-6xl text-[var(--card-accent)]">{item.glyph}</div><h2 className="relative mt-5 font-serif text-3xl font-black">{zh ? item.titleZh : item.title}</h2><p className="relative mt-2 text-sm italic text-white/45">{zh ? item.subtitleZh : item.subtitle}</p><div className="relative mt-auto pt-7"><Link href={item.route} className="flex min-h-12 items-center justify-between border border-white/20 px-4 font-mono text-[10px] font-black uppercase tracking-wider transition group-hover:border-[var(--card-accent)] group-hover:text-[var(--card-accent)]"><span>{zh ? '开始校准' : 'Begin calibration'}</span><span>→</span></Link></div></article> })}</div></div></main>
}
