'use client'

import { useMemo, useState } from 'react'
import { useLocale } from 'next-intl'
import InstrumentShell, { InstrumentButton, InstrumentResult } from './InstrumentShell'
import { useInstrumentProgress } from './useInstrumentProgress'
import { MOBIUS_FIXED_LEVELS, findMobiusSolution, generateMobiusLevel, toggleMobiusSwitch, traceMobius, type MobiusTrace } from '@/lib/impossible-instruments/mobius-mailroom'
import { dailySeed } from '@/lib/impossible-instruments/core'

export default function MobiusMailroomGame() {
  const zh = useLocale() === 'zh'; const [levelIndex, setLevelIndex] = useState(0); const [infiniteRound, setInfiniteRound] = useState(0)
  const level = useMemo(() => levelIndex < 6 ? MOBIUS_FIXED_LEVELS[levelIndex] : generateMobiusLevel(`${dailySeed('mobius-mailroom')}:${infiniteRound}`, infiniteRound > 2 ? 'hard' : 'standard'), [levelIndex, infiniteRound])
  const [switches, setSwitches] = useState(level.initial); const [trace, setTrace] = useState<MobiusTrace | null>(null); const [runs, setRuns] = useState(0); const [hints, setHints] = useState(0); const [score, setScore] = useState(0); const [solved, setSolved] = useState(false); const [hintIndex, setHintIndex] = useState<number | null>(null); const { best, record } = useInstrumentProgress('mobius-mailroom')
  const run = () => { const result = traceMobius(level, switches); const nextRuns = runs + 1; setTrace(result); setRuns(nextRuns); if (result.delivered) { const earned = Math.max(150, 650 - nextRuns * 50 - hints * 80); setScore((v) => v + earned); setSolved(true); record(Math.min(levelIndex + 1, 6), score + earned) } }
  const toggle = (index: number) => { if (solved) return; setSwitches((v) => toggleMobiusSwitch(v, index)); setTrace(null); setHintIndex(null) }
  const hint = () => { const solution = findMobiusSolution(level); const index = solution?.findIndex((value, i) => value !== switches[i]) ?? -1; if (index >= 0) { setHintIndex(index); setHints((v) => v + 1) } }
  const next = () => { const ni = levelIndex < 5 ? levelIndex + 1 : 6; const nr = levelIndex < 5 ? infiniteRound : infiniteRound + 1; const nl = ni < 6 ? MOBIUS_FIXED_LEVELS[ni] : generateMobiusLevel(`${dailySeed('mobius-mailroom')}:${nr}`, nr > 2 ? 'hard' : 'standard'); setLevelIndex(ni); setInfiniteRound(nr); setSwitches(nl.initial); setTrace(null); setRuns(0); setHints(0); setScore(score); setSolved(false); setHintIndex(null) }
  const visited = new Set(trace?.states.map((s) => `${s.side}:${s.position}`) ?? [])
  const aside = <><div className="border border-white/15 bg-black/20 p-4"><p className="font-mono text-[9px] tracking-widest text-[var(--instrument-accent)]">{zh ? '投递地址' : 'DELIVERY ADDRESS'}</p><p className="mt-3 font-mono text-2xl font-black">SIDE {level.target.side === 0 ? 'A' : 'B'} · {level.target.position + 1}</p><p className="mt-2 text-xs text-white/40">{zh ? '越过纸带边缘会翻面并反转方向。' : 'Crossing an edge flips the strip and reverses direction.'}</p></div><div className="grid grid-cols-2 gap-2"><InstrumentButton onClick={run} primary>{zh ? '启动邮车' : 'Run courier'}</InstrumentButton><InstrumentButton onClick={hint} disabled={solved}>{zh ? '标记路标' : 'Mark switch'}</InstrumentButton></div>{trace && <div className={`border p-4 font-mono text-xs ${trace.delivered ? 'border-[#72c99a] text-[#72c99a]' : 'border-[#d56a6a] text-[#dc8585]'}`}>{trace.delivered ? (zh ? '包裹已送达' : 'PARCEL DELIVERED') : trace.loop ? (zh ? '路线进入循环' : 'ROUTE LOOPED') : (zh ? '邮车未能送达' : 'DELIVERY MISSED')}</div>}<div className="border border-white/10 p-3 font-mono text-xs text-white/45">RUNS {runs} · BEST {best}</div>{solved && <InstrumentResult title={zh ? '双面投递完成' : 'Two-sided delivery complete'} detail={`${runs} runs`} onNext={next} nextLabel={levelIndex < 5 ? (zh ? '下一记录' : 'Next record') : (zh ? '持续观测' : 'Infinite observation')} />}</>
  return <InstrumentShell id="mobius-mailroom" level={Math.min(levelIndex + 1, 6)} levelCount={6} score={score} hints={hints} aside={aside}><div><p className="mb-5 font-mono text-[10px] tracking-[.2em] text-white/40">{zh ? '点击路标改变邮车方向' : 'TOGGLE SIGNS TO REDIRECT THE COURIER'}</p>{([0, 1] as const).map((side) => <div key={side} className={`mb-5 border p-3 ${side === 0 ? 'border-[#56d6c9]/40 bg-[#102725]' : 'border-[#d692e8]/35 bg-[#29172d]'}`}><div className="mb-3 flex justify-between font-mono text-[9px]"><span>SIDE {side === 0 ? 'A' : 'B'}</span><span>{side === level.target.side ? 'TARGET FACE' : 'REVERSE FACE'}</span></div><div className="grid gap-2" style={{ gridTemplateColumns: `repeat(${level.length},minmax(0,1fr))` }}>{switches.map((active, index) => { const target = side === level.target.side && index === level.target.position; return <button key={index} type="button" onClick={() => toggle(index)} disabled={solved} aria-pressed={active} className={`relative aspect-square min-h-11 border font-mono text-lg transition ${hintIndex === index ? 'animate-pulse border-[var(--instrument-accent)] bg-[var(--instrument-accent)] text-black' : visited.has(`${side}:${index}`) ? 'border-white bg-white/15' : 'border-white/15 hover:border-[var(--instrument-accent)]'}`}>{target ? '⌂' : active ? '↩' : '→'}</button> })}</div></div>)}</div></InstrumentShell>
}
