'use client'

import { useMemo, useState } from 'react'
import { useLocale } from 'next-intl'
import InstrumentShell, { InstrumentButton, InstrumentResult } from './InstrumentShell'
import { useInstrumentProgress } from './useInstrumentProgress'
import { SHADOW_FIXED_LEVELS, generateShadowLevel, getShadowHint, isShadowSolved, traceShadows, type ShadowDirection } from '@/lib/impossible-instruments/shadow-cartographer'
import { dailySeed } from '@/lib/impossible-instruments/core'

const ARROWS = ['↓', '←', '↑', '→']
export default function ShadowCartographerGame() {
  const zh = useLocale() === 'zh'; const [levelIndex, setLevelIndex] = useState(0); const [infiniteRound, setInfiniteRound] = useState(0)
  const level = useMemo(() => levelIndex < 6 ? SHADOW_FIXED_LEVELS[levelIndex] : generateShadowLevel(`${dailySeed('shadow-cartographer')}:${infiniteRound}`, infiniteRound > 2 ? 'hard' : 'standard'), [levelIndex, infiniteRound])
  const [direction, setDirection] = useState<ShadowDirection>(level.initialDirection); const [moves, setMoves] = useState(0); const [hints, setHints] = useState(0); const [score, setScore] = useState(0); const [solved, setSolved] = useState(false); const [hintText, setHintText] = useState(''); const { best, record } = useInstrumentProgress('shadow-cartographer')
  const shadows = new Set(traceShadows(level.size, level.blockers, direction)); const target = new Set(level.target); const forbidden = new Set(level.forbidden)
  const rotate = (step: -1 | 1) => { if (solved) return; const nextDirection = ((direction + step + 4) % 4) as ShadowDirection; const nextMoves = moves + 1; setDirection(nextDirection); setMoves(nextMoves); setHintText(''); if (isShadowSolved(level, nextDirection, level.blockers)) { const earned = Math.max(120, 500 - nextMoves * 25 - hints * 70); setScore((v) => v + earned); setSolved(true); record(Math.min(levelIndex + 1, 6), score + earned) } }
  const hint = () => { setHintText(getShadowHint(level, direction)); setHints((v) => v + 1) }
  const next = () => { const ni = levelIndex < 5 ? levelIndex + 1 : 6; const nr = levelIndex < 5 ? infiniteRound : infiniteRound + 1; const nl = ni < 6 ? SHADOW_FIXED_LEVELS[ni] : generateShadowLevel(`${dailySeed('shadow-cartographer')}:${nr}`, nr > 2 ? 'hard' : 'standard'); setLevelIndex(ni); setInfiniteRound(nr); setDirection(nl.initialDirection); setMoves(0); setHints(0); setSolved(false); setHintText('') }
  const aside = <><div className="border border-white/15 bg-black/20 p-4"><p className="font-mono text-[9px] tracking-widest text-[var(--instrument-accent)]">{zh ? '光源方位' : 'LIGHT BEARING'}</p><p className="mt-3 text-center text-5xl text-[var(--instrument-accent)]">{ARROWS[direction]}</p><div className="mt-4 grid grid-cols-2 gap-2"><InstrumentButton onClick={() => rotate(-1)}>↺ 45°</InstrumentButton><InstrumentButton onClick={() => rotate(1)}>↻ 45°</InstrumentButton></div></div><div className="border border-white/15 p-4 text-xs leading-6 text-white/45">{zh ? '琥珀格必须处于阴影，红色感光格必须保持明亮。移动的是光，不是地图。' : 'Amber cells must be shadowed. Red sensor cells must remain lit. Move the light, not the map.'}</div>{hintText && <p className="border border-[var(--instrument-accent)]/40 p-3 text-xs text-[var(--instrument-accent)]">{zh ? `尝试向${hintText === 'clockwise' ? '顺时针' : '逆时针'}旋转。` : `Try rotating ${hintText}.`}</p>}<InstrumentButton onClick={hint} disabled={solved}>{zh ? '读取光差' : 'Read light delta'}</InstrumentButton><div className="border border-white/10 p-3 font-mono text-xs text-white/45">MOVES {moves} · BEST {best}</div>{solved && <InstrumentResult title={zh ? '阴影地图吻合' : 'Shadow map aligned'} detail={`${moves} moves`} onNext={next} nextLabel={levelIndex < 5 ? (zh ? '下一记录' : 'Next record') : (zh ? '持续观测' : 'Infinite observation')} />}</>
  return <InstrumentShell id="shadow-cartographer" level={Math.min(levelIndex + 1, 6)} levelCount={6} score={score} hints={hints} aside={aside}><div className="mx-auto max-w-[640px]"><div className="mb-4 flex justify-between font-mono text-[9px] tracking-wider text-white/35"><span>PHOTOSENSITIVE PLATE</span><span>{level.size}×{level.size}</span></div><div className="grid aspect-square border border-white/15 bg-[#e9dfca] p-2" style={{ gridTemplateColumns: `repeat(${level.size},1fr)` }}>{Array.from({ length: level.size * level.size }, (_, index) => { const row = Math.floor(index / level.size); const col = index % level.size; const key = `${row}:${col}`; const blocker = level.blockers.some((b) => b.row === row && b.col === col); const shadow = shadows.has(key); return <div key={key} className={`relative border border-[#5a5042]/15 transition-colors duration-300 ${shadow ? 'bg-[#25221e]' : 'bg-[#eee5d3]'}`}>{target.has(key) && <span className="absolute inset-1 border-2 border-[#d69a3b]" aria-label="Target shadow" />}{forbidden.has(key) && <span className="absolute inset-1 flex items-center justify-center text-[#c84b40]" aria-label="Must stay lit">×</span>}{blocker && <span className="absolute inset-[22%] z-10 rotate-45 bg-[#6f5533] shadow-md" aria-label="Blocker" />}</div> })}</div></div></InstrumentShell>
}
