'use client'

import { useMemo, useState } from 'react'
import { useLocale } from 'next-intl'
import AdvancedPuzzleShell, { AdvancedButton } from './AdvancedPuzzleShell'
import { useAdvancedProgress } from './useAdvancedProgress'
import { FOLD_FIXED_LEVELS, availableFolds, findFoldSolution, foldPaper, generateFoldLevel, isFoldSolved, type FoldDirection, type PaperState } from '@/lib/advanced-puzzles/foldspace-atelier'
import { dateSeed } from '@/lib/puzzle-core/random'

const LABELS: Record<FoldDirection, { en: string; zh: string; glyph: string }> = {
  left: { en: 'Fold left inward', zh: '左侧向内折', glyph: '→│' }, right: { en: 'Fold right inward', zh: '右侧向内折', glyph: '│←' }, up: { en: 'Fold top inward', zh: '上方向内折', glyph: '↓' }, down: { en: 'Fold bottom inward', zh: '下方向内折', glyph: '↑' }
}
const MARKS = ['◆', '●', '▲']

export default function FoldspaceAtelierGame() {
  const zh = useLocale() === 'zh'; const [levelIndex, setLevelIndex] = useState(0); const [infiniteRound, setInfiniteRound] = useState(0)
  const level = useMemo(() => levelIndex < 6 ? FOLD_FIXED_LEVELS[levelIndex] : generateFoldLevel(`${dateSeed('foldspace-atelier')}:${infiniteRound}`, infiniteRound > 2 ? 8 : 4, infiniteRound > 3 ? 8 : 4, infiniteRound > 2 ? 4 : 3), [levelIndex, infiniteRound])
  const [paper, setPaper] = useState<PaperState>(level.initial); const [history, setHistory] = useState<PaperState[]>([]); const [folds, setFolds] = useState(0); const [hints, setHints] = useState(0); const [score, setScore] = useState(0); const [solved, setSolved] = useState(false); const [hintDirection, setHintDirection] = useState<FoldDirection | null>(null); const { best, record } = useAdvancedProgress('foldspace-atelier')
  const targetMark = new Map<string, string>(); level.targets.forEach((target, index) => { targetMark.set(target.first, MARKS[index]); targetMark.set(target.second, MARKS[index]) })
  const fold = (direction: FoldDirection) => { if (solved) return; const nextPaper = foldPaper(paper, direction); if (!nextPaper) return; const nextFolds = folds + 1; setHistory((items) => [...items, paper]); setPaper(nextPaper); setFolds(nextFolds); setHintDirection(null); if (isFoldSolved(nextPaper, level.targets)) { const earned = Math.max(180, 800 - nextFolds * 45 - hints * 90); setScore((value) => value + earned); setSolved(true); record(Math.min(levelIndex + 1, 6), score + earned) } }
  const undo = () => { const previous = history.at(-1); if (!previous || solved) return; setPaper(previous); setHistory((items) => items.slice(0, -1)); setFolds((value) => Math.max(0, value - 1)); setHintDirection(null) }
  const reset = () => { setPaper(level.initial); setHistory([]); setFolds(0); setSolved(false); setHintDirection(null) }
  const hint = () => { const path = findFoldSolution(paper, level.targets, 6); if (path?.[0]) { setHintDirection(path[0]); setHints((value) => value + 1) } }
  const next = () => { const ni = levelIndex < 5 ? levelIndex + 1 : 6; const nr = levelIndex < 5 ? infiniteRound : infiniteRound + 1; const nl = ni < 6 ? FOLD_FIXED_LEVELS[ni] : generateFoldLevel(`${dateSeed('foldspace-atelier')}:${nr}`, nr > 2 ? 8 : 4, nr > 3 ? 8 : 4, nr > 2 ? 4 : 3); setLevelIndex(ni); setInfiniteRound(nr); setPaper(nl.initial); setHistory([]); setFolds(0); setHints(0); setSolved(false); setHintDirection(null) }
  const aside = <><div className="border border-white/15 bg-black/20 p-4"><p className="font-mono text-[9px] tracking-widest text-[var(--advanced-accent)]">{zh ? '叠合目标' : 'OVERLAY TARGETS'}</p><div className="mt-4 space-y-3">{level.targets.map((target, index) => { const done = paper.stacks.some((stack) => { const ids = new Set(stack.map((layer) => layer.id)); return ids.has(target.first) && ids.has(target.second) }); return <div key={target.first} className={`flex items-center justify-between border p-3 font-mono text-xs ${done ? 'border-[#78d2a2] text-[#78d2a2]' : 'border-white/15 text-white/55'}`}><span>{MARKS[index]} {target.first.toUpperCase()}</span><span>＋</span><span>{MARKS[index]} {target.second.toUpperCase()}</span></div> })}</div></div><div className="grid grid-cols-2 gap-2"><AdvancedButton onClick={undo} disabled={!history.length || solved}>↶ {zh ? '撤销' : 'Undo'}</AdvancedButton><AdvancedButton onClick={reset}>↻ {zh ? '展开' : 'Reset'}</AdvancedButton></div><AdvancedButton onClick={hint} disabled={solved}>{zh ? '显示下一折' : 'Show next fold'}</AdvancedButton><div className="border border-white/10 p-3 font-mono text-xs text-white/40">FOLDS {folds} · LAYERS {Math.max(...paper.stacks.map((stack) => stack.length))} · BEST {best}</div>{solved && <div className="border border-[#78d2a2] bg-[#11291d] p-5 text-center"><p className="font-serif text-2xl font-black text-[#78d2a2]">{zh ? '纸层全部吻合' : 'All layers aligned'}</p><AdvancedButton onClick={next} primary>{levelIndex < 5 ? (zh ? '下一张纸' : 'Next sheet') : (zh ? '每日折界' : 'Daily fold')}</AdvancedButton></div>}</>
  return <AdvancedPuzzleShell title="FOLDSPACE ATELIER" titleZh="折界工坊" eyebrow="THE CABINET / PAPER ENGINE 21" intro="Fold a two-sided paper world until distant marks occupy the same physical layer." introZh="折叠一张拥有正反面的纸世界，让相隔遥远的印记在同一物理位置重合。" accent="#f1b866" level={Math.min(levelIndex + 1, 6)} levelCount={6} score={score} aside={aside}><div><div className="mb-4 flex items-center justify-between font-mono text-[9px] text-white/35"><span>TWO-SIDED SHEET</span><span>{paper.width}×{paper.height}</span></div><div className="mx-auto grid w-full max-w-[680px] gap-1 bg-[#34281d] p-2 transition-all duration-300" style={{ gridTemplateColumns: `repeat(${paper.width},minmax(0,1fr))`, aspectRatio: `${paper.width}/${paper.height}` }}>{paper.stacks.map((stack, index) => { const top = stack.at(-1)!; const marks = stack.map((layer) => targetMark.get(layer.id)).filter(Boolean); return <div key={`${top.id}-${index}`} className={`relative flex min-h-11 items-center justify-center overflow-hidden border font-mono text-[10px] font-black transition ${top.face === 0 ? 'border-[#b99463] bg-[#eadbbf] text-[#493721]' : 'border-[#68849a] bg-[#b9ced7] text-[#283c48]'}`}><span className="absolute left-1 top-0.5 text-[7px] opacity-45">{top.face === 0 ? 'F' : 'B'}·{stack.length}</span><span>{top.id.toUpperCase()}</span>{marks.length > 0 && <span className="absolute bottom-0.5 right-1 text-sm text-[#bd4e3c]">{marks.join('')}</span>}</div> })}</div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4">{(['left','right','up','down'] as FoldDirection[]).map((direction) => <button key={direction} type="button" onClick={() => fold(direction)} disabled={!availableFolds(paper).includes(direction) || solved} className={`min-h-14 border px-2 font-mono text-[10px] font-black uppercase transition disabled:opacity-15 ${hintDirection === direction ? 'animate-pulse border-[var(--advanced-accent)] bg-[var(--advanced-accent)] text-[#21170c]' : 'border-white/20 hover:border-[var(--advanced-accent)] hover:text-[var(--advanced-accent)]'}`}><span className="mr-2 text-lg">{LABELS[direction].glyph}</span>{zh ? LABELS[direction].zh : LABELS[direction].en}</button>)}</div></div></AdvancedPuzzleShell>
}
