'use client'

import { useMemo, useState } from 'react'
import { useLocale } from 'next-intl'
import AdvancedPuzzleShell, { AdvancedButton } from './AdvancedPuzzleShell'
import { useAdvancedProgress } from './useAdvancedProgress'
import { PROOF_FIXED_LEVELS, applyProofMove, generateProofLevel, getProvableMoves, isProofSolved, type ProofBoard, type ProofMove, type ProofValue } from '@/lib/advanced-puzzles/proof-habitat'
import { dateSeed } from '@/lib/puzzle-core/random'

export default function ProofHabitatGame() {
  const zh = useLocale() === 'zh'; const [levelIndex, setLevelIndex] = useState(0); const [infiniteRound, setInfiniteRound] = useState(0)
  const level = useMemo(() => levelIndex < 6 ? PROOF_FIXED_LEVELS[levelIndex] : generateProofLevel(`${dateSeed('proof-habitat')}:${infiniteRound}`, infiniteRound > 2 ? 6 : 5), [levelIndex, infiniteRound])
  const [board, setBoard] = useState<ProofBoard>(level.initial); const [selected, setSelected] = useState<number | null>(null); const [proofLog, setProofLog] = useState<ProofMove[]>([]); const [message, setMessage] = useState(''); const [hints, setHints] = useState(0); const [score, setScore] = useState(0); const [solved, setSolved] = useState(false); const { best, record } = useAdvancedProgress('proof-habitat')
  const provable = getProvableMoves(board, level.clues); const moveMap = new Map(provable.map((move) => [move.cell, move])); const selectedClues = selected === null ? [] : level.clues.filter((clue) => clue.cells.includes(selected)).slice(0, 6)
  const claim = (value: ProofValue) => { if (selected === null || solved) return; const proof = moveMap.get(selected); if (!proof || proof.value !== value) { setMessage(zh ? '当前证据还不能证明这个结论。猜测已被拒绝。' : 'Current evidence cannot prove that claim. Guessing was rejected.'); return } const nextBoard = applyProofMove(board, proof); setBoard(nextBoard); setProofLog((log) => [...log, proof]); setSelected(null); setMessage(proof.reason); if (isProofSolved(nextBoard, level)) { const earned = Math.max(200, 1000 - hints * 100); setScore((s) => s + earned); setSolved(true); record(Math.min(levelIndex + 1, 6), score + earned) } }
  const hint = () => { const move = provable[0]; if (move) { setSelected(move.cell); setMessage(zh ? `证据指向第 ${move.cell + 1} 格。你仍需判断它的状态。` : `Evidence points to cell ${move.cell + 1}. You must still name its state.`); setHints((v) => v + 1) } }
  const next = () => { const ni = levelIndex < 5 ? levelIndex + 1 : 6; const nr = levelIndex < 5 ? infiniteRound : infiniteRound + 1; const nl = ni < 6 ? PROOF_FIXED_LEVELS[ni] : generateProofLevel(`${dateSeed('proof-habitat')}:${nr}`, nr > 2 ? 6 : 5); setLevelIndex(ni); setInfiniteRound(nr); setBoard(nl.initial); setSelected(null); setProofLog([]); setMessage(''); setHints(0); setSolved(false) }
  const aside = <><div className="border border-white/15 bg-black/20 p-4"><p className="font-mono text-[9px] tracking-widest text-[var(--advanced-accent)]">{zh ? '证明协议' : 'PROOF PROTOCOL'}</p><p className="mt-3 text-xs leading-6 text-white/50">{zh ? '选择生物并提交“稳定”或“异常”。只有当前线索能严格推出结论时，仪器才会接受。' : 'Select an organism and claim stable or anomaly. The instrument accepts only conclusions forced by current clues.'}</p></div>{selected !== null && <div className="border border-[var(--advanced-accent)]/40 p-4"><p className="font-mono text-[9px] text-[var(--advanced-accent)]">CELL {selected + 1}</p><div className="mt-3 grid grid-cols-2 gap-2"><AdvancedButton onClick={() => claim('stable')} primary>{zh ? '稳定' : 'Stable'}</AdvancedButton><AdvancedButton onClick={() => claim('anomaly')}>{zh ? '异常' : 'Anomaly'}</AdvancedButton></div><div className="mt-4 space-y-2">{selectedClues.map((clue) => <p key={clue.id} className="text-xs text-white/45">{clue.label}: {clue.requiredStable}/{clue.cells.length} stable</p>)}</div></div>}<AdvancedButton onClick={hint} disabled={solved}>{zh ? '指出可证明格' : 'Locate provable cell'}</AdvancedButton><div className="border border-white/10 p-3 font-mono text-xs text-white/40">PROOFS {proofLog.length}/{level.solution.length - 1} · BEST {best}</div>{solved && <div className="border border-[#75d5a0] bg-[#112a1d] p-5 text-center"><p className="font-serif text-2xl font-black text-[#75d5a0]">{zh ? '生态证明闭合' : 'Habitat proof complete'}</p><AdvancedButton onClick={next} primary>{levelIndex < 5 ? (zh ? '下一记录' : 'Next record') : (zh ? '每日生态' : 'Daily habitat')}</AdvancedButton></div>}</>
  return <AdvancedPuzzleShell title="PROOF HABITAT" titleZh="证明生态园" eyebrow="THE CABINET / PROOF ENGINE 20" intro="A living deduction grid that refuses every guess. Each accepted claim must cite a complete proof." introZh="一座拒绝任何猜测的演绎生态。每个被接受的结论都必须拥有完整证明。" accent="#7bd89d" level={Math.min(levelIndex + 1, 6)} levelCount={6} score={score} aside={aside}><div><div className="mb-4 flex justify-between font-mono text-[9px] text-white/35"><span>DEDUCTION FIELD</span><span>{board.filter(Boolean).length}/{board.length}</span></div><div className="grid aspect-square gap-1.5" style={{ gridTemplateColumns: `repeat(${level.size},1fr)` }}>{board.map((value, index) => <button key={index} type="button" onClick={() => { if (!value && !solved) { setSelected(index); setMessage('') } }} disabled={Boolean(value) || solved} aria-label={`Organism ${index + 1}${value ? ` ${value}` : ''}`} className={`relative min-h-11 border font-mono text-lg font-black transition focus:outline-none focus:ring-2 focus:ring-[var(--advanced-accent)] ${selected === index ? 'border-[var(--advanced-accent)] bg-[var(--advanced-accent)]/15' : value === 'stable' ? 'border-[#75d5a0]/50 bg-[#143124] text-[#75d5a0]' : value === 'anomaly' ? 'border-[#e47575]/50 bg-[#351919] text-[#e47575]' : 'border-white/15 bg-white/[.03] hover:border-white/40'}`}>{value === 'stable' ? '●' : value === 'anomaly' ? '×' : index + 1}{value && <span className="absolute bottom-1 right-1 text-[7px] opacity-50">{index === level.initial.findIndex((v) => v !== null) ? 'GIVEN' : 'PROOF'}</span>}</button>)}</div><p className="mt-5 min-h-12 border-l-2 border-[var(--advanced-accent)] px-4 py-2 text-sm text-white/55" aria-live="polite">{message || (zh ? '选择一个尚未判定的生物，然后提交你能够证明的状态。' : 'Select an unresolved organism, then submit the state you can prove.')}</p></div></AdvancedPuzzleShell>
}
