'use client'

import { useEffect, useMemo, useState } from 'react'
import { useLocale } from 'next-intl'
import AdvancedPuzzleShell, { AdvancedButton } from './AdvancedPuzzleShell'
import { useAdvancedProgress } from './useAdvancedProgress'
import { ADVANCED_PROGRESS_KEY, parseAdvancedProgress } from '@/lib/advanced-puzzles/core'
import { generateRoomPuzzle, isRoomCodeCorrect, roomShareGrid } from '@/lib/advanced-puzzles/room-nineteen'
import { INSTRUMENT_PROGRESS_KEY, parseInstrumentProgress } from '@/lib/impossible-instruments/core'
import { dateSeed } from '@/lib/puzzle-core/random'

export default function RoomNineteenGame() {
  const zh = useLocale() === 'zh'; const [chapter, setChapter] = useState(1); const [archivePower, setArchivePower] = useState(0)
  const seed = chapter <= 6 ? `room-nineteen:chapter-${chapter}` : dateSeed('room-nineteen')
  const puzzle = useMemo(() => generateRoomPuzzle(seed), [seed]); const [digits, setDigits] = useState([0, 0, 0, 0]); const [revealed, setRevealed] = useState<boolean[]>([true, false, false, false]); const [emergencyReveals, setEmergencyReveals] = useState(0); const [attempts, setAttempts] = useState(0); const [score, setScore] = useState(0); const [solved, setSolved] = useState(false); const [message, setMessage] = useState(''); const [copied, setCopied] = useState(false); const { best, record } = useAdvancedProgress('room-nineteen')
  useEffect(() => { try { const instruments = parseInstrumentProgress(localStorage.getItem(INSTRUMENT_PROGRESS_KEY)); const advanced = parseAdvancedProgress(localStorage.getItem(ADVANCED_PROGRESS_KEY)); const completed = Object.values(instruments.completed).filter((value) => (value ?? 0) >= 6).length + Object.values(advanced.completed).filter((value) => (value ?? 0) >= 6).length; setArchivePower(completed); const unlocked = Math.min(4, 1 + Math.floor(completed / 2)); setRevealed(Array.from({ length: 4 }, (_, index) => index < unlocked)); setChapter(Math.min(7, (advanced.completed['room-nineteen'] ?? 0) + 1)) } catch {} }, [])
  const turnDial = (index: number, delta: number) => setDigits((current) => current.map((digit, position) => position === index ? (digit + delta + 10) % 10 : digit))
  const reveal = (index: number) => { if (revealed[index]) return; setRevealed((items) => items.map((value, position) => position === index ? true : value)); setEmergencyReveals((value) => value + 1) }
  const submit = () => { const nextAttempts = attempts + 1; setAttempts(nextAttempts); if (!isRoomCodeCorrect(digits, puzzle)) { setMessage(zh ? '锁芯拒绝了这组数字。房间仍然沉默。' : 'The lock rejected that sequence. The room remains silent.'); return } const earned = Math.max(150, 1200 - nextAttempts * 80 - emergencyReveals * 140); setScore((value) => value + earned); setSolved(true); setMessage(zh ? '第十九号房的门锁已经打开。' : 'The lock to Room Nineteen has opened.'); record(Math.min(chapter, 6), score + earned) }
  const next = () => { const nextChapter = chapter < 6 ? chapter + 1 : 7; setChapter(nextChapter); setDigits([0,0,0,0]); const unlocked = Math.min(4, 1 + Math.floor(archivePower / 2)); setRevealed(Array.from({ length: 4 }, (_, index) => index < unlocked)); setEmergencyReveals(0); setAttempts(0); setSolved(false); setMessage(''); setCopied(false) }
  const copyResult = async () => { try { await navigator.clipboard.writeText(roomShareGrid(puzzle, attempts, emergencyReveals)); setCopied(true) } catch { setMessage(zh ? '无法访问剪贴板。' : 'Clipboard unavailable.') } }
  const aside = <><div className="border border-white/15 bg-black/20 p-4"><p className="font-mono text-[9px] tracking-widest text-[var(--advanced-accent)]">{zh ? '馆藏共振' : 'ARCHIVE RESONANCE'}</p><p className="mt-3 font-mono text-3xl font-black">{archivePower}</p><p className="mt-2 text-xs leading-5 text-white/45">{zh ? '每修复两台仪器，就能自动解封一条房间线索。未解封线索仍可紧急开启，但会降低得分。' : 'Every two stabilized games reveal one clue. Locked clues can be opened in an emergency at a score cost.'}</p></div><div className="border border-white/10 p-3 font-mono text-xs text-white/40">ATTEMPTS {attempts} · REVEALS {emergencyReveals} · BEST {best}</div>{solved && <div className="border border-[var(--advanced-accent)] bg-[#231b0f] p-5 text-center"><p className="font-serif text-2xl font-black text-[var(--advanced-accent)]">{zh ? '房门已经回应' : 'The room answered'}</p><div className="mt-4 grid gap-2"><AdvancedButton onClick={copyResult}>{copied ? (zh ? '已复制' : 'Copied') : (zh ? '复制非剧透结果' : 'Copy result')}</AdvancedButton><AdvancedButton onClick={next} primary>{chapter < 6 ? (zh ? '下一层门锁' : 'Next lock') : (zh ? '今日房间' : 'Today’s room')}</AdvancedButton></div></div>}</>
  return <AdvancedPuzzleShell title="ROOM NINETEEN" titleZh="第十九号房" eyebrow="THE CABINET / RESTRICTED META-ARCHIVE" intro="Fragments from every instrument converge on one lock. Decode four independent clues and open the room." introZh="所有仪器留下的残片最终汇聚到同一把锁。解读四条独立线索，打开房间。" accent="#d7ad59" level={Math.min(chapter, 6)} levelCount={6} score={score} aside={aside}><div><div className="grid gap-3 sm:grid-cols-2">{puzzle.clues.map((clue, index) => <div key={clue.id} className={`min-h-36 border p-4 transition ${revealed[index] ? 'border-[#d7ad59]/40 bg-[#2a2112]' : 'border-white/10 bg-black/25'}`}><div className="flex items-center justify-between"><span className="font-mono text-[9px] tracking-widest text-white/35">FRAGMENT {index + 1} · {clue.id.toUpperCase()}</span><span className="text-lg">{['⌘','◉','◷','◇'][index]}</span></div>{revealed[index] ? <><p className="mt-4 font-serif text-3xl font-black text-[var(--advanced-accent)]">{clue.encoded}</p><p className="mt-3 text-xs leading-5 text-white/50">{zh ? clue.detailZh : clue.detail}</p></> : <button type="button" onClick={() => reveal(index)} className="mt-5 min-h-12 w-full border border-dashed border-white/20 font-mono text-[9px] uppercase text-white/40 hover:border-[var(--advanced-accent)] hover:text-[var(--advanced-accent)]">{zh ? '紧急开启线索' : 'Emergency reveal'}</button>}</div>)}</div><div className="mt-7 border-y border-white/10 bg-black/20 p-4 sm:p-7"><p className="text-center font-mono text-[9px] tracking-[.25em] text-white/35">FOUR-DIAL CABINET LOCK</p><div className="mx-auto mt-5 grid max-w-lg grid-cols-4 gap-2 sm:gap-4">{digits.map((digit, index) => <div key={index} className="grid gap-1"><button type="button" aria-label={`Increase dial ${index + 1}`} onClick={() => turnDial(index, 1)} disabled={solved} className="min-h-11 border border-white/15 hover:border-[var(--advanced-accent)]">＋</button><div className="flex aspect-[3/4] items-center justify-center border-2 border-[var(--advanced-accent)] bg-[#19150f] font-mono text-[clamp(2rem,10vw,4rem)] font-black text-[var(--advanced-accent)]">{digit}</div><button type="button" aria-label={`Decrease dial ${index + 1}`} onClick={() => turnDial(index, -1)} disabled={solved} className="min-h-11 border border-white/15 hover:border-[var(--advanced-accent)]">−</button></div>)}</div><div className="mx-auto mt-6 max-w-lg"><AdvancedButton onClick={submit} disabled={solved} primary>{zh ? '尝试开启第十九号房' : 'Attempt Room Nineteen'}</AdvancedButton></div></div><p className="mt-5 min-h-12 border-l-2 border-[var(--advanced-accent)] px-4 py-2 text-sm text-white/55" aria-live="polite">{message || (zh ? '四条线索使用四种不同编码，但都只指向一个数字。' : 'Four fragments use four different encodings, but each points to one digit.')}</p></div></AdvancedPuzzleShell>
}
